Fix for accepting spaces in arguments, at instantiation of Audioset.
lukefahr/audioset pull request #1
Opened 2018-10-06 05:05 UTC by somsubhojit1988

2018-10-07 16:52 UTC, lukefahr commented
Can you make this into 4 different pull requests?  I want to make some tweaks to 1 or 2 of them.  

-A

2018-10-08 03:49 UTC, somsubhojit1988 commented
Actually they are 4 different commits. I had pushed them incrementally, onto my master and made pull request from my master to your's which is the  reason why they are being shown as consolidated. I will make 4 different branches and make pull requests for each of them separately.

2018-10-08 12:58 UTC, lukefahr requested changes

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +                 data_dir=None, logLvl=logging.INFO, sampling_rate=None):
Can you move sampling_rate to it's own line above data_dir.

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +                 data_dir=None, logLvl=logging.INFO, sampling_rate=None):
And give it a default value?

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +                                   logLvl=logLvl, sampling_rate=sampling_rate)
again, sampling_rate before logLvl

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> -    #
Don't delete the '#' lines

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +        fname = ddir + '/'+ ytid + '.wav'
don't delete space

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +    def __init__(this, data_dir=None, sampling_rate = None,logLvl= logging.WARN):
We might want to rethink this a little better.  I'm worried you are going to end up with a bunch of downsampled clips in the same data directory as non-downsampled clips, and audioset won't know which are which.  Perhaps we want to put in a warning or something if the pre-downloaded clip is a sampling rate less than what you have requested?  Or re-download it?

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +        this.sampling_rate = sampling_rate
move above this.mydir

2018-10-08 12:58 UTC, lukefahr commented on audioset.py
> +
remove spaces?

2018-10-08 13:00 UTC, lukefahr commented
Commit 1 is merged.  I split Commit 2 into 2 different commits and merged.  Commit 3 needs some work.  Commit 4 will merge once 3 is fixed.  Please make a seperate branch for Commit 3, and another one for Commit 4.  

Thanks

2018-10-08 19:30 UTC, closed without merging